Added support for restrictedToMinimumLevel to Serilog.
aws/aws-logging-dotnet pull request #165
Opened 2021-05-18 16:59 UTC by ashishdhingra

*Issue #:* #164 

*Description of changes:*
Added support for restrictedToMinimumLevel to Serilog.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-05-18 17:18 UTC, normj requested changes

2021-05-18 17:18 UTC, normj commented on src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
> -    <Version>3.0.0</Version>
Since this is a feature lets set this to 3.1.0

2021-05-18 17:25 UTC, normj approved these changes

2021-05-20 17:11 UTC, 96malhar approved these changes

2021-05-21 18:34 UTC, merged