feat: Introduction of new GitHub issue forms
aws/aws-logging-dotnet pull request #190
Opened 2022-03-03 23:43 UTC by aaoswal

*Issue #, if available:*

*Description of changes:*
- Added new GitHub issue forms for bug reports, documentation and feature requests.
- Removed old GitHub issue templates for bug reports, documentation and feature requests.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-30 18:28 UTC, ganeshnj requested changes

2022-03-30 18:28 UTC, ganeshnj commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +name: "\U0001F41B Bug Report"
add a required control for repro solution, this will save back and forth.

2022-03-30 18:34 UTC, ganeshnj requested changes

2022-03-30 18:34 UTC, ganeshnj commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    attributes:
use placeholder property to guide customer what could be a potential value for each type.

2022-03-31 23:53 UTC, ganeshnj approved these changes

2022-04-01 16:59 UTC, kellertk commented
Superseded by #194

2022-04-01 16:59 UTC, closed without merging